# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          cache: 'npm'
      - name: Clean Install deps
        run: npm ci
      - name: Build Angular Element Web Component
        run: npm run wc:build
      - name: Check Linting
        run: npm run lint
      - name: Check CSS Linting
        run: npm run lint:css
      - name: Run tests and collect code coverage
        run: |
          npm run test
          ls -l coverage
          ls -l coverage/table-multiplication
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.COVERALLS_REPO_SECRET }}
          path-to-lcov: ./coverage/table-multiplication/lcov.info
      - name: copy static assets
        run: npm run wc:copy-static
      - name: Change BASE HREF
        run: node build/replace-base-href.mjs
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload static/ repository
          path: 'static/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
